services:
  api:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8888:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py

  qdrant:
    image: qdrant/qdrant:v1.3.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_HTTP_PORT=6333
      - QDRANT_GRPC_PORT=6334

volumes:
  qdrant_data:
