services:
  api:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8888:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: run.py
